framework:
    cache:
        pools:
            cache.password_reset_requests:
                adapter: cache.adapter.filesystem
    lock:
        resources:
            password_reset_requests: flock
    rate_limiter:
        password_reset_requests:
            policy: fixed_window
            limit: '%env(int:PASSWORD_RESET_REQUEST_LIMIT)%'
            interval: '%env(PASSWORD_RESET_REQUEST_INTERVAL)%'
            cache_pool: cache.password_reset_requests
            lock_factory: lock.password_reset_requests.factory
